version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: heavyreserve-api:latest
    container_name: app-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: ${APP_DB_CONNECTION}
      ConnectionStrings__Redis: ${REDIS_CONNECTION}
      RabbitMQ__ConnectionString: ${RABBITMQ_CONNECTION}
      Keycloak__Authority: ${KEYCLOAK_AUTHORITY}
      Keycloak__MetadataAddress: ${KEYCLOAK_METADATA}
      Keycloak__ExternalUrl: ${KEYCLOAK_EXTERNAL_URL}
      Keycloak__ClientId: ${KEYCLOAK_CLIENT_ID}
      Keycloak__Audience: ${KEYCLOAK_AUDIENCE}
      Keycloak__Issuer: ${KEYCLOAK_ISSUER}

      # New Relic Hardcoded Fix
      NEW_RELIC_APP_NAME: "High-Concurrency-Reservation-Engine"
      NEW_RELIC_LICENSE_KEY: "50cb468f56d1a1a4ba03f357e84c13eb1d02NRAL"
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
      NEW_RELIC_LOG_CONSOLE: "true"

      # .NET Profiler Settings
      CORECLR_ENABLE_PROFILING: "1"
      CORECLR_PROFILER: "{36032161-FFC0-4B61-B559-F6C5D41BAE5A}"
      CORECLR_NEWRELIC_HOME: "/usr/local/newrelic-dotnet-agent"
      CORECLR_PROFILER_PATH: "/usr/local/newrelic-dotnet-agent/libNewRelicProfiler.so"

    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }
      keycloak: { condition: service_started }

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 25s
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: app-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ReservationDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ReservationDb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: app-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: app-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: app-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_URL: http://localhost:8081
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      postgres: { condition: service_healthy }
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  keycloak_data: